# Generated by Django 4.2.7 on 2023-11-10 13:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("file", models.FileField(upload_to="", verbose_name="File")),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="MIME type"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Medium",
                "verbose_name_plural": "Media",
            },
        ),
    ]
