# Generated by Django 4.2.7 on 2023-12-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Archived At"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Published At"
            ),
        ),
    ]
